baseURL = "https://hair2020.github.io/"
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "zh-cn"

# theme
theme = "LoveIt"

# themes directory
themesDir = "themes"

# website title
title = "HAIR's world"

enableRobotsTXT = true

enableGitInfo = false

# whether to use emoji code
enableEmoji = true

# The directory to where Hugo will write the final static site (the HTML files etc.). Default is public.
publishDir = "docs"

[params]
  # LoveIt theme version
  version = "0.2.X"

  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"

  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""

  # date format
  dateFormat = "2006-01-02"

  images = ["/logo.png"]

  # 页面头部导航栏配置
  [params.header]
    # 导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    mobileMode = "auto"

    # 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # title name
      name = " HAIR's blog"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      # pre = "<i class='far fa-kiss-wink-heart fa-fw'></i>"
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = "<i class='far :no_smoking: fa-fw'></i>"
      # 是否为标题显示打字机动画
      typeit = false

  # 页面底部信息配置
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2022
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # license info (HTML format is supported)
    # 是否显示 Hugo 和主题信息
    hugo = false

  # Section (所有文章) 页面配置
  [params.section]
    # special amount of posts in each section page
    # section 页面每页显示文章数量
    paginate = 20

    # 日期格式 (月和日)
    dateFormat = "01-02"

    # RSS 文章数目
    rss = 10

  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20

    # 日期格式 (月和日)
    dateFormat = "01-02"

    # RSS 文章数目
    rss = 10

  # Page config
  # 文章页面配置
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    # 是否使用 twemoji
    twemoji = true
    # 是否使用 lightgallery
    lightgallery = true
    # 是否使用 ruby 扩展语法
    ruby = true
    # 是否使用 fraction 扩展语法
    fraction = true
    # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否显示原始 Markdown 文档内容的链接
    linkToMarkdown = false
    # 是否在 RSS 中显示全文内容
    rssFullText = false

    # 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true

    # 代码配置
    [params.page.code]
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 10
    
    # KaTeX 数学公式配置 (KaTeX https://katex.org/)
    [params.page.math]
      enable = false
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""

      # KaTeX 插件 copy_tex
      copyTex = true

      # KaTeX 插件 mhchem
      mhchem = true

    # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true

    # 文章页面的分享信息设置
    [params.page.share]
      enable = false
      Twitter = true
      Facebook = true
      

    # 第三方库配置
    [params.page.library]
      [params.page.library.css]
      [params.page.library.js]
    
    # 页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = "xxxx"
        logoUrl = "/images/avatar.png"

  # TypeIt config
  # TypeIt 配置
  [params.typeit]
    # 每一步的打字速度 (单位是毫秒)
    speed = 100
    # 光标的闪烁速度 (单位是毫秒)
    cursorSpeed = 1000
    # 光标的字符 (支持 HTML 格式)
    cursorChar = "|"
    # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
    duration = -1

 # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = "/images/Apple-Devices-Preview.png"
    # 缩略图 URL
    thumbnailUrl = "/images/screenshot.png"


  # Cookie 许可配置
  [params.cookieconsent]
    enable = false
    # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  # 第三方库文件的 CDN 设置
  [params.cdn]
    data = "jsdelivr.yml"
  # 兼容性设置
  [params.compatibility]
    polyfill = false
    objectFit = false

# Hugo 解析文档的配置
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true

  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 作者配置
[author]
  name = "hair"
  email = "a644661457@gmail.com"
  link = ""

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  # posts = ":filename"

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Analytics config
# 网站分析配置
# 我给塞到head/links.html里了，能用

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[languages.zh-cn]
  weight = 2
  # 网站语言, 仅在这里 CN 大写
  languageCode = "zh-CN"
  # 语言名称
  languageName = "简体中文"
  # 是否包括中日韩文字
  hasCJKLanguage = true
  # 默认每页列表显示的文章数目
  paginate = 12
  # [UA-XXXXXXXX-X] 谷歌分析代号
  googleAnalytics = ""
  # 版权描述，仅仅用于 SEO
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
  # 菜单配置
  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      name = "所有文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""
      weight = 4
    [[languages.zh-cn.menu.main]]
      identifier = "github"
      pre = "<i class='fab fa-github fa-fw'></i>"
      post = ""
      name = ""
      url = "https://github.com/dillonzq/LoveIt"
      title = "GitHub"
      weight = 6
  [languages.zh-cn.params]
    # 网站描述
    description = "关于 LoveIt 主题"
    # 网站关键词
    keywords = ["Theme", "Hugo"]
    # 应用图标配置
    [languages.zh-cn.params.app]
      # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
      title = "LoveIt"
      # 是否隐藏网站图标资源链接
      noFavicon = false
      # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
      svgFavicon = ""
      # Android 浏览器主题色
      themeColor = "#ffffff"
      # Safari 图标颜色
      iconColor = "#5bbad5"
      # Windows v8-10 磁贴颜色
      tileColor = "#da532c"
    # 搜索配置
    [languages.zh-cn.params.search]
      enable = true
      # 搜索引擎的类型 ("lunr", "algolia")
      type = "algolia"
      # 文章内容最长索引长度
      contentLength = 4000
      # 搜索框的占位提示语
      placeholder = ""
      # 最大结果数目
      maxResultLength = 10
      # 结果内容片段长度
      snippetLength = 50
      # 搜索结果中高亮部分的 HTML 标签
      highlightTag = "em"
      # 是否在搜索索引中使用基于 baseURL 的绝对路径
      absoluteURL = false
      [languages.zh-cn.params.search.algolia]
        index = "index.zh-cn"
        appID = "PASDMWALPK"
        searchKey = "b42948e51daaa93df92381c8e2ac0f93"
    # 主页信息设置
    [languages.zh-cn.params.home]
      # RSS 文章数目
      rss = 10
      # 主页个人信息
      [languages.zh-cn.params.home.profile]
        enable = true
        # Gravatar 邮箱，用于优先在主页显示的头像
        gravatarEmail = ""
        # 主页显示头像的 URL
        avatarURL = "/images/avatar.png"
        # 主页显示的网站标题 (支持 HTML 格式)
        title = "头发"
        # 主页显示的网站副标题
        subtitle = "就像光明划过黑夜"
        # 是否为副标题显示打字机动画
        typeit = true
        # 是否显示社交账号
        social = true
        # 免责声明 (支持 HTML 格式)
        disclaimer = ""
      # 主页文章列表
      [languages.zh-cn.params.home.posts]
        enable = true
        # 主页每页显示文章数量
        paginate = 6
    # 主页的社交信息设置
    [languages.zh-cn.params.social]
      GitHub = "hair2020"
      Twitter = ""
      Facebook = ""
      Telegram = "Hardenest"
      Bilibili = "516401105"
      Email = "644661457@qq.com"